#if !defined(ENTITY_H)
#include "len_string.h"
enum PointDisplayType
{
    POINT_DISPLAY_TYPE_NONE = 0,
    POINT_DISPLAY_TYPE_QUAD = 1 << 0,
    POINT_DISPLAY_TYPE_CIRCLE = 1 << 1
};

enum LineDisplayType
{
    LINE_DISPLAY_TYPE_NONE = 0,
    LINE_DISPLAY_TYPE_STROKE = 1 << 0
};

enum MeshDisplayType
{
    MESH_DISPLAY_TYPE_NONE = 0,
    MESH_DISPLAY_TYPE_WIRES = 1 << 0,
    MESH_DISPLAY_TYPE_FILL = 1 << 1
};

enum QuadType
{
    QUAD_TYPE_SCREEN_SPACE = 0,
    QUAD_TYPE_WORLD_SPACE = 1 << 0
};

enum ComponentType
{
    COMPONENT_TYPE_NONE = 0,
    COMPONENT_TYPE_PT = 1 << 0,
    COMPONENT_TYPE_SIZE = 1 << 1,
    COMPONENT_TYPE_LINE = 1 << 2,
    COMPONENT_TYPE_HAS_CHILDREN = 1 << 3,
    COMPONENT_TYPE_COLOR = 1 << 4,
    COMPONENT_TYPE_MASS = 1 << 5,
    COMPONENT_TYPE_VELOCITY = 1 << 6,
    COMPONENT_TYPE_BOID = 1 << 7,
    COMPONENT_TYPE_FLAGGED_DELETION = 1 << 8, //TODO Deprecate this
    COMPONENT_TYPE_FROZEN = 1 << 9,
    COMPONENT_TYPE_QUAD = 1 << 10,
    COMPONENT_TYPE_GLYPH = 1 << 11,
    COMPONENT_TYPE_STATIC_MESH = 1 << 12,
    COMPONENT_TYPE_MESH_MEMBER = 1 << 13,
    COMPONENT_TYPE_POSITION = 1 << 14,
    COMPONENT_TYPE_TEXTURE = 1 << 15,
    COMPONENT_TYPE_AGENT_TYPE = 1 << 16,
    COMPONENT_TYPE_TIMERS = 1 << 17,
    COMPONENT_TYPE_HAS_PERSISTENT_TARGET = 1 << 18,
    COMPONENT_TYPE_PLAYER_CONTROLLABLE = 1 << 19,
    COMPONENT_TYPE_CLICKABLE_REFLECTION = 1 << 20,
    COMPONENT_TYPE_SAVED_W_LEVEL = 1 << 21,
    COMPONENT_TYPE_NOT_NULL = 1 << 22,
    COMPONENT_TYPE_PLAYER_TONGUE = 1 << 23,
    COMPONENT_TYPE_CLICKABLE_GIZMO = 1 << 24
};
#include <unordered_map>
#include "ComponentType.inl"

#define ENTITY_H
#endif
